config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :users
  resources :products
  root 'products#index'
  get '/cart' , to: 'purchases#cart'
  get '/login', to: 'users#login', as: :login
  post '/sign_out', to: 'users#sign_out', as: :sign_out
  post '/sign_in', to: 'users#sign_in', as: :sign_in
  post '/sign_up', to: 'users#sign_up', as: :sign_up
  post '/add_to_cart/:id',  to: 'purchases#add_to_cart', as: :add_to_cart
  post '/change_quantity/:id', to: 'purchases#change_quantity', as: :change_quantity
  post '/finish_order', to: 'purchases#finish_order', as: :finish_order
  post '/search', to: 'products#search', as: :search
  #get '/search', to: 'products#search', as: :search
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :purchases, dependent: :destroy
  has_many :products, through: :purchases
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_admin, only: :edit

  # GET /users or /users.json
  def index
    #render plain: "OK" , status: :forbidden
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def login

  end

  def sign_in
    user = User.find_by(email: user_params['email'])
    if user.nil?
      flash[:notice] = "Ilyen email címmel felhasználó nem található"
      redirect_to login_path
      return
    end
    if user.password == user_params['password']
      session['user_id'] = user.id
      redirect_to root_path
    else
      flash[:notice] = "Helytelen jelszó"
      redirect_to login_path
    end
  end

  def sign_out
    session.destroy
    redirect_to root_path
  end

  def sign_up
    if params['user']['confirmation_password'] == user_params['password']
      begin
        user = User.create!(user_params)
      rescue StandardError
        flash[:notice] = "Ezzel az email címmel már létezik felhasználó"
        redirect_to login_path
        return
      end
      session['user_id'] = user.id
      flash[:notice] = "Sikeres regisztráció"
      redirect_to root_path
    end
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def require_admin
    p ""
    render status: :forbidden, plain: "You do not have access to this page." unless current_user&.admin
  end
  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= form_with url: sign_in_path, model: User.new do |form| %>
        <%= form.label :email %>
        <%= form.text_field :email %></br>
        <%= form.label :password %>
        <%= form.text_field :password %></br>
        <%= form.submit 'Belépés'%>
      <% end %>

    </div>
    <div class="col-6">
      <%= form_with url: sign_up_path, model: User.new do |form| %>
        <%= form.text_field :last_name , placeholder: 'Vezetéknév'%>
        <%= form.text_field :first_name , placeholder: 'Keresztnév'%></br>
        <%= form.text_field :email , placeholder: 'email'%></br>
        <%= form.text_field :password ,placeholder: 'jelszó'%></br>
        <%= form.text_field :confirmation_password ,placeholder: 'jelszó megerősítése'%></br>
        <%= form.submit 'Regisztráció'%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>