config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :users
  resources :products
  root 'products#index'
  get '/cart' , to: 'purchases#cart'
  get '/login', to: 'users#login', as: :login
  post '/sign_out', to: 'users#sign_out', as: :sign_out
  post '/sign_in', to: 'users#sign_in', as: :sign_in
  post '/sign_up', to: 'users#sign_up', as: :sign_up
  post '/add_to_cart/:id',  to: 'purchases#add_to_cart', as: :add_to_cart
  post '/change_quantity/:id', to: 'purchases#change_quantity', as: :change_quantity
  post '/finish_order', to: 'purchases#finish_order', as: :finish_order
  post '/search', to: 'products#search', as: :search
  #get '/search', to: 'products#search', as: :search
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[ show edit update destroy ]

  # GET /purchases or /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1 or /purchases/1.json
  def show
  end

  def add_to_cart
    user = current_user
    product = Product.find(params['id'])
    purchase = user.purchases.find_by product_id: product.id
    if !purchase.nil?
      purchase.quantity += 1
      purchase.save
      return
    end
    Purchase.create!(user: user,product: product , quantity: 1 , purchased: false )
  end

  def change_quantity
    purchase = Purchase.find(params['id'])
    purchase.quantity += params['amount'].to_i
    purchase.save!
    if purchase.quantity == 0
      purchase.destroy
    end
    redirect_to cart_path
  end

  def finish_order
    current_user.purchases.each do |purchase|
      if purchase.quantity > purchase.product.quantity
        flash[:notice] = "Nincs elég #{purchase.product.name}"
        redirect_to cart_path
        return
      end
    end

    current_user.purchases.each do |purchase|
      product = purchase.product
      product.quantity -= purchase.quantity
      if product.quantity == 0
        product.status = Product.statuses[:out_of_stock]
      end
      product.save
      purchase.update!(purchased: true)
    end
    flash[:notice] = "Sikeres vásárlás"
    redirect_to root_path
  end

  def cart

  end
  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases or /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: "Purchase was successfully created." }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: "Purchase was successfully updated." }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: "Purchase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def purchase_params
      params.require(:purchase).permit(:user_id, :product_id, :quantity)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_with(model: purchase) do |form| %>
  <% if purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/purchases/cart.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <table>
    <%current_user.purchases.each do |purchase| %>
        <tr>
          <td><%=purchase.product.name %></td>
          <td><%=purchase.product.price %></td>
          <td><%=purchase.quantity %>
          <td><%=button_to '+', change_quantity_path(purchase), params:{amount: '1'} , method: :post %></td>
          <td><%=button_to '-', change_quantity_path(purchase), params:{amount: '-1'} , method: :post %></td>
        </tr>
      <% end %>
        <tr>
          <td colspan="2">Összesen</td>
          <td colspan="3"><%=current_user.purchases.sum do |purchase|%>
              <% purchase.product.price*purchase.quantity%>
            <% end %>
          </td>
        </tr>

      </table>
    </div>
    <div class="col-6">
      <%=button_to 'Rendelés', finish_order_path, method: :post %>
    </div>
  </div>
</div>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchases</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.user_id %></td>
        <td><%= purchase.product_id %></td>
        <td><%= purchase.quantity %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @purchase.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @purchase.product_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @purchase.quantity %>
</p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>