config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :users
  resources :products
  root 'products#index'
  get '/cart' , to: 'purchases#cart'
  get '/login', to: 'users#login', as: :login
  post '/sign_out', to: 'users#sign_out', as: :sign_out
  post '/sign_in', to: 'users#sign_in', as: :sign_in
  post '/sign_up', to: 'users#sign_up', as: :sign_up
  post '/add_to_cart/:id',  to: 'purchases#add_to_cart', as: :add_to_cart
  post '/change_quantity/:id', to: 'purchases#change_quantity', as: :change_quantity
  post '/finish_order', to: 'purchases#finish_order', as: :finish_order
  post '/search', to: 'products#search', as: :search
  #get '/search', to: 'products#search', as: :search
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  enum status: [:in_stock , :out_of_stock]
  has_many :purchases, dependent: :destroy
  has_many :users, through: :purchases

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end


  def search
    @products = Product.all.select{|product| product.name.include?(params['search'])}
    render :index
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :status, :image , :quantity)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%=link_to product.name, product %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.status == 'in_stock' ? 'Raktáron' : 'Nincs Raktáron' %>
        <%if !current_user.nil? %>
            <td><%= button_to 'Kosárba', add_to_cart_path(product.id) ,method: :post %></td>
          <%end %>
        <%if current_user&.admin%>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if current_user&.admin%>
<%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div><%= @product.name %></div>
  <div class="row">
    <div class="col">
      <strong>Description:</strong>
      <%= @product.description %>
    </div>
    <div class="col">
      <%= image_tag @product.image , :size => 20*20  %>
    </div>
  </div>
  <div class="row">
      <div class="col">
        <div>
          <strong>Price:</strong>
          <%= @product.price %>
        </div>
        <div>
          <strong>Status:</strong>
          <%= @product.status %>
        </div>
      </div>
    <%if !current_user.nil? %>
      <div><%= button_to 'Kosárba', add_to_cart_path(@product.id) ,method: :post %></div>
    <%end %>
  </div>
  <div>

</div>

<%if current_user&.admin %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<%end %>