config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :users
  resources :products
  root 'products#index'
  get '/cart' , to: 'purchases#cart'
  get '/login', to: 'users#login', as: :login
  post '/sign_out', to: 'users#sign_out', as: :sign_out
  post '/sign_in', to: 'users#sign_in', as: :sign_in
  post '/sign_up', to: 'users#sign_up', as: :sign_up
  post '/add_to_cart/:id',  to: 'purchases#add_to_cart', as: :add_to_cart
  post '/change_quantity/:id', to: 'purchases#change_quantity', as: :change_quantity
  post '/finish_order', to: 'purchases#finish_order', as: :finish_order
  post '/search', to: 'products#search', as: :search
  #get '/search', to: 'products#search', as: :search
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hazifeladat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </head>

  <body>
  <p id="notice" class="text-center"><%= notice %></p>
  <div class="container">
    <div class="row">
      <div class="col-2">
        <div>Menu</div>
        <%=link_to "Főoldal",products_path, type:"button", class:"btn btn-dark"%>
        <%if current_user.nil?%>
          <%=link_to "Bejelentkezés", login_path , type:'button', class:'btn btn-secondary' %>
          <%else %>
          <%=button_to "Kijelentkezés", sign_out_path , method: :post, type:'button', class:'btn btn-secondary'%>
          <%end %>
        <%= form_with url: search_path do |form| %>
          <%= form.text_field :search , placeholder: 'Keresés', size: '3' %></br>
          <%= form.submit 'Keresés'%>
        <% end %>
        <%if !current_user.nil? %>
            <div><%="#{current_user&.first_name} bejelentkezve" %></div>
          <%end %>
      </div>
      <div class="col-10">
        <%if !current_user.nil? %>
        <div><%=link_to "Kosár", '/cart'  ,type:"button", class:"btn btn-light"%></div>
          <% end %>
      <%=yield %>
      </div>
    </div>
  </div>
  </body>
</html>